use std::fmt::Debug;

#[derive(PartialEq)]
pub enum Token {
    Illegal,
    Eof,
    Ident(String),
    String(String),
    Int(i64),
    Percent,
    Assign,
    Plus,
    Minus,
    Bang,
    Asterisk,
    Slash,
    Lt,
    LtorEq,
    Gt,
    GtorEq,
    Comma,
    Semicolon,
    Lparen,
    Rparen,
    Lbrace,
    Rbrace,
    Function,
    Let,
    True,
    False,
    If,
    Else,
    Return,
    Eq,
    NotEq,
    Lbracket,
    Rbracket,
}

impl Debug for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::Eq => write!(f, "Equal"),
            Token::NotEq => write!(f, "Not equal"),
            Token::True => write!(f, "True"),
            Token::False => write!(f, "False"),
            Token::If => write!(f, "If"),
            Token::Else => write!(f, "Else"),
            Token::Return => write!(f, "Return"),
            Token::Asterisk => write!(f, "Asterisk"),
            Token::Slash => write!(f, "Slash"),
            Token::Lt => write!(f, "Less than"),
            Token::Gt => write!(f, "Greater than"),
            Token::Minus => write!(f, "Minus"),
            Token::Bang => write!(f, "Bang"),
            Token::Illegal => write!(f, "Illegal"),
            Token::Eof => write!(f, "Eof"),
            Token::Ident(ident) => write!(f, "Ident: {}", ident),
            Token::Int(int) => write!(f, "Int: {}", int),
            Token::String(string) => write!(f, "String: {}", string),
            Token::Assign => write!(f, "Assign"),
            Token::Plus => write!(f, "Plus"),
            Token::Comma => write!(f, "Comma"),
            Token::Semicolon => write!(f, "Semicolon"),
            Token::Lparen => write!(f, "Lparen"),
            Token::Rparen => write!(f, "Rparen"),
            Token::Lbrace => write!(f, "Lbrace"),
            Token::Rbrace => write!(f, "Rbrace"),
            Token::Function => write!(f, "Function"),
            Token::Let => write!(f, "Let"),
            Token::Percent => write!(f, "Percent"),
            Token::LtorEq => write!(f, "Less than or Equal"),
            Token::GtorEq => write!(f, "Greater than or Equal"),
            Token::Lbracket => write!(f, "Lbracket"),
            Token::Rbracket => write!(f, "Rbracket"),
        }
    }
}
